<?php echo $this->render("includes/header.phtml"); ?>

<body>

    <!-- Navigation -->
    <?php echo $this->render("includes/topnav.phtml"); ?>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('<?php echo BASEURL; ?>/public/img/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <hr class="small">
                        <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			
			
				<?php 
					foreach ($this->blogs as $key=>$value) {
				?>
			
                <div class="post-preview">
                    <a href="/blog/post/<?php echo $value['id']; ?>">
                        <h2 class="post-title">
                            <?php echo $value['title']; ?>
                        </h2>
                        <h3 class="post-subtitle">
                            <?php echo $value['content']; ?>
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="/users/profile/<?php echo $value['user_id']; ?>"><?php echo $value['username']; ?></a> on <?php echo date("F j, Y", strtotime($value['created_at'])); ?></p>
                </div>
                <hr>
				<?php } ?>

				
				
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="/blog/posts/back/10">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <?php echo $this->render("includes/footer.phtml"); ?>

    <!-- jQuery -->
	<?php echo $this->render("includes/javascript.phtml"); ?>

</body>

</html>
