    <!-- jQuery -->
    <script src="<?php echo BASEURL; ?>/public/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo BASEURL; ?>/public/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="<?php echo BASEURL; ?>/public/js/jqBootstrapValidation.js"></script>

    <!-- Theme JavaScript -->
    <script src="<?php echo BASEURL; ?>/public/js/clean-blog.min.js"></script>