<?php echo $this->render("includes/header.phtml"); ?>

<body>

    <!-- Navigation -->
	<?php echo $this->render("includes/topnav.phtml"); ?>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('<?php echo BASEURL; ?>/public/img/post-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1><?php echo $this->blog['title']; ?></h1>
                        <h2 class="subheading"><?php echo substr($this->blog['title'], 0, 40); ?></h2>
                        <span class="meta">Posted by <a href="#"><?php echo $this->blog['username']; ?></a> on <?php echo date("F j, Y", strtotime($this->blog['created_at'])); ?></span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p>
					<?php echo $this->blog['content']; ?>
					</p>
                </div>
            </div>
        </div>
    </article>

    <hr>

    <!-- Footer -->
	<?php echo $this->render("includes/footer.phtml"); ?>

    <!-- jQuery -->
	<?php echo $this->render("includes/javascript.phtml"); ?>

</body>

</html>
